### ISSUE TITLE
ＵＩ調整

### ISSUE THREAD

**Issue by pinl** [johnlinp/frnci#10]
現在介面呈現欄位區分不夠清楚
項目名稱可以更凸顯一點嗎
有個框或是顏色不一樣之類

![2015-06-10 19 22 46](https://cloud.githubusercontent.com/assets/10533109/8081393/f1ec32fc-0fa6-11e5-9e30-44a53f44254d.png)

PS. 如果有時間的話，想客製化每個當地人的背景
（每個地陪的背景會不一樣，會跟他想帶旅人去哪裡有關）

**Comment by johnlinp** [comment]
"客製化每個當地人的背景" 這件事請另外記一個 issue 喔!
