### ISSUE TITLE
讓人留下 email 的地方

### ISSUE THREAD

**Issue by pinl** [johnlinp/frnci#15]
希望可以用明顯一點的方式呈現
透明度太高  滑下去其實看不太到那邊可以填寫email

**Comment by pinl** [comment]
這部分有辦法不要是透明的嗎？因為瀏覽還是不太清楚，要仔細看才會知道可以填寫email
然後覺得原本小框比較好看（現在變成一整個長的）

**Comment by johnlinp** [comment]
由於 placeholder 要有一點透明，才能顯示出使用者的 email 才是重要的內容，所以用粗體來讓它比較清楚，而沒有調透明度。
