### ISSUE TITLE
Move "Why FRNCI" under "How it works"

### ISSUE THREAD

**Issue by johnlinp** [johnlinp/frnci#39]

**Comment by pinl** [comment]
<img width="760" alt="2015-07-04 11 21 29" src="https://cloud.githubusercontent.com/assets/10533109/8506275/da4436d6-223e-11e5-9179-3891efd347d4.png">
1. 文案有小修：

為什麼要用 F R N C i ？

【如果你是這樣的旅人】

想探索私房景點或探索當地文化的你
想和興趣相似的新朋友深度交流的你

【如果你是這樣的當地人】

想認識世界各地不同文化的朋友的你
想分享更多你的文化和生活體驗的你
1.  橘色背景的透明度可以調高一點，現在有點太飽和了
2. 點選「往下尋找當地朋友」的按鈕之後
   就往下滑到地區分類

**Comment by johnlinp** [comment]
那請問英文版的文案有要修嗎？

**Comment by pinl** [comment]
WHY F R N C i ?
【If you are a traveler ...】
wanting to explore hidden spots and local spirit. 
wanting to meet locals with similar interest
【If you are a local ...】
wanting to make friends from all over the world
wanting to share local culture and your daily life

TRY FRNCi ! 
Redefine your journey with us!

Look for local friends

**Comment by pinl** [comment]
間隔的調整：
1. 『歡迎你和我們一起重新定義「旅行」！』距離上一行資訊間隔一行就可以了
1. 「往下尋找地陪」下方不用空格，橘色背景延伸到按鈕的下一行就好

**Comment by pinl** [comment]
英文也記得調整喔～

**Comment by pinl** [comment]
「為什麼要用 FRNCI ？」和『歡迎你和我們一起重新定義「旅行」！』麻煩加粗

**Comment by johnlinp** [comment]
Fix in 3c5e2864f8916a919beece5fca89e25a23197547
