### ISSUE TITLE
當地人頁面用column並排呈現 

### ISSUE THREAD

**Issue by pinl** [johnlinp/frnci#40]
當地人的頁面呈現修改成一次就能看到三個人 （圖示只有兩欄因為字太大塞不下，但希望可以以三欄的格式呈現）

<img width="766" alt="2015-07-04 08 58 22" src="https://cloud.githubusercontent.com/assets/10533109/8505895/e0dbf010-222a-11e5-8694-d1a24e3e0dca.png">

**Comment by pinl** [comment]
手機版的一次呈現一欗即可

**Comment by pinl** [comment]
地陪頁面的個人資訊的間隔不要那麼大
每段資訊之間間隔一行就好
1. 第一列到「我想要和旅人…」
2. 「我想要和旅人…」和「可以一起去」
3. 「我想要和旅人…」和「我想媒合」

**Comment by pinl** [comment]
地陪資訊頁的某些區塊好像會跑掉？
例如：一次只出現兩欄或一欄

**Comment by johnlinp** [comment]
Workaround: 增加 "我想要和旅人…" 的高度。

**Comment by johnlinp** [comment]
關於 "地陪頁面的個人資訊的間隔不要那麼大" ，也是採用 workaround 的方式：
把每個當地人加上框，就顯得間隔沒有那麼大。

**Comment by johnlinp** [comment]
四周都加框好像有點難看，所以改成只有加底線。
