### ISSUE TITLE
興趣類別裡增加地點資訊

### ISSUE THREAD

**Issue by pinl** [johnlinp/frnci#41]
興趣類別點進去後的當地人頁面，需要增加地點資訊的呈現，不然不知道是要去哪裡？

直接參考檔案裡面的 place 
https://docs.google.com/spreadsheets/d/1kqy2t7MEqMlh2L6-R8WCsRfurz6ez32m9Y0xxN-2w4Y/edit#gid=0

如圖增加一列："Where we could meet..." 和 「可以一起去...」
<img width="431" alt="2015-07-04 09 06 49" src="https://cloud.githubusercontent.com/assets/10533109/8505920/10745fdc-222c-11e5-9815-4b4e16b4df71.png">

**Comment by johnlinp** [comment]
因為覺得 "按照地點" 進去，比方說 "西部" ，還是應該要可以看到是到台中還是彰化，所以不止 "按照興趣" ，連 "按照地點" 也顯示了地點資訊。
